name: DungeonTowerReMake
version: 1.0
main: tororo1066.dungeontower.DungeonTower
api-version: 1.17

depend:
  - MythicMobs
  - WorldEdit
softdepend:
  - Multiverse-Core
  - Multiverse-Portals
  - MultiWorld
load: POSTWORLD
commands:
  dungeon:
    permission: dungeon.user
    aliases:
      - tower
      - dt
  dungeontask:
    permission: dungeon.task
    aliases:
      - dtask